Update Goals.md
amongus-02/tacofalls pull request #105
Opened 2021-03-10 16:38 UTC by norman-promise-neverland

2021-03-10 16:40 UTC, bailey-botany requested changes

2021-03-10 16:40 UTC, bailey-botany commented on Goals.md
> +- [ ] Beauty
add a new thingk
jhkghfhgftrdtrygh
jkuyfvnbm
hgjhgjhfufttytfgh

2021-03-10 16:44 UTC, norman-promise-neverland commented on Goals.md
> +- [ ] Beauty
@bailey-botany thanks!

2021-03-11 16:38 UTC, rizel-botany approved these changes

2021-03-12 01:55 UTC, closed without merging